import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';
// import Header from "./Components/Header"
// import Popular from "./Components/Popular";
// import Recomended from "./Components/Recomended"
import Footer from "./Components/Footer"
// import React from "react";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta-sans', 
  weight: ['400', '500', '600', '700'], 
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });


export const metadata: Metadata = {
  title: "Car Rental Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable}  antialiased`}
      >
        {/* <Header /> */}
        {children}
        {/* <Popular/>
        <Recomended/> */}
        <Footer/>
      </body>
    </html>
  );
}
