import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { CartProvider } from "./Components/cartContext";
import { FavoritesProvider } from "./tracking/FavoritesContext";
import ChatWidget from "./Components/ChatWidget";
import "./globals.css";
import Footer from "./Components/Footer";
import { CategoryProvider } from "./Components/CategoryContext";
import HeaderWrapper from "./Components/HeaderWrapper";

export const metadata: Metadata = {
  title: "Car Rental Web",
  description: "Generated by create next app",
  icons: "/favicon.ico"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" suppressHydrationWarning>
        <body className="antialiased flex flex-col min-h-screen" suppressHydrationWarning>
          <CategoryProvider>
            <CartProvider>
              <FavoritesProvider>
                <HeaderWrapper />
                <div className="flex-1">
                  {children}
                </div>
                <ChatWidget />
              </FavoritesProvider>
            </CartProvider>
          </CategoryProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}